project:
  type: website

website:
  title: "Farid Musayev"
  background: white
  site-url: https://faridmusayev.github.io
  navbar:
    pinned: false
    search: false

    right:
#      - text: "Blog"
#        file: blog.qmd
      - text: "Projects"
        menu:
          - p1.qmd
          - p2.qmd
      - text: "About"
        file: about.qmd
format:
  html:
    theme: spacelab
    css: styles.css
    toc: true
