project:
  type: website

website:
  title: "Farid Musayev"
  navbar:
    #background: "#2a4073"
  #  foreground: "white"
    pinned: true
    search: false

    right:
      - text: "Home"
        file: index.qmd
      - text: "Projects"
        menu:
          - p1.qmd
          - computations.ipynb
      - text: "About"
        file: about.qmd
format:
  html:
    theme: spacelab
    css: styles.css
    toc: true
